[platform]
display_name =
name =
; proto_id: 0 = OAuth2, 1 = PNBA
proto_id =
; cat_id: 0 = Email, 1 = Message, 2 = Text, 3 = Bridge
cat_id =
; true or false
supports_offline_first =
icon_svg =
icon_png =

[author]
name = Afkanerd Developers
email = developers@smswithoutborders.com
